### ISSUE TITLE
 nginx: [emerg] host not found in upstream "registry"

### ISSUE THREAD

**Issue by alexeyzimarev** [Egregors/private-docker-registry#1]
When nginx proceeds to startup, everything crashes with this error:

> nginx: [emerg] host not found in upstream "registry" in 
> /etc/nginx/vhosts/cachereg.apptrium.io.conf:23

**Comment by egregors** [comment]
I see.. This repo like kind of legacy. Looks like we just should move it from Nginx to traefik. I believe it will be the easiest solution

**Comment by alexeyzimarev** [comment]
Strangely enough, it started to work when I tried today.
